name: Run Tests

on:
  push:
    branches:
      - main  # Trigger tests on commits to the main branch
      - '**'  # Optional: Include all branches
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Run Tests
      run: |
        python -m unittest discover -s tests  # Ensure tests are in a `tests/` folder
